# Generated by Django 4.1.3 on 2022-12-03 03:40

from django.db import migrations
from django.utils.text import slugify


def popular_slugs(apps, schema_editor):
    Modulo = apps.get_model('modulos', 'Modulo')

    for modulo in Modulo.objects.all():
        modulo.slug = slugify(modulo.titulo)
        modulo.save()


class Migration(migrations.Migration):
    dependencies = [
        ('modulos', '0002_slug_nulo_para_migracao_de_dados'),
    ]

    operations = [
        migrations.RunPython(popular_slugs)
    ]
