name: Python Project

on: pull_request

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalação de dependências
      run: |
        pip install pipenv
        pipenv sync --dev

    - name: Lint com flake8
      run: |
        pipenv run flake8 .

    - name: Testes automáticos com pytest
      run: |
        pipenv run pytest Django_Dev-Pro