name: Status da Build

on: pull_request

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Instalação de dependências
      run: |
        pip install pipenv
        pipenv sync --dev
        pipenv install codecov

    - name: Cópia de variáveis de configurações para arquivo .env
      run: |
        cp contrib/env-sample .env

    - name: Lint com flake8
      run: |
        pipenv run flake8 --max-line-length=120 --exclude=.venv --ignore=F401,W503

    - name: Testes automáticos com pytest
      run: |
        pipenv run pytest Django_DevPro --nomigrations --cov=Django_DevPro

    - name: Postando cobertura de código com Codecov
      env:
        CODECOV_TOKEN: "efa0c093-7276-4675-a216-f67ab72c25c1"
      run: |
        pipenv run codecov